name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
    branches:
      - main
      - master

jobs:
  cd-pipeline:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Start Deploying EC2..."
            cd /home/ubuntu

            echo "Cleaning up Docker resources..."
            sudo docker image prune -af

            TAG=${{ github.event.workflow_run.head_sha }}
            USERNAME=$(grep '^DOCKERHUB_USERNAME=' .env | cut -d'=' -f2)

            echo "Retry pull image"
            pull_with_retry() {
              local image=$1
              for i in {1..10}; do
                if sudo docker pull $image; then
                  return 0
                fi
                echo "Image $image chưa có, retry $i/10 sau 8s..."
                sleep 8
              done
              return 1
            }

            sudo sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=$TAG/" .env || echo "IMAGE_TAG=$TAG" >> .env

            pull_with_retry "$USERNAME/booking-backend:$TAG" || exit 1
            pull_with_retry "$USERNAME/booking-frontend:$TAG" || exit 1 

            sudo docker compose up -d --force-recreate
            sudo docker image prune -f
            echo "Deploy EC2 Successfully!"